export const INIT = "INIT";
export const SEARCH_IMG = "SEARCH_IMG";
export const COLLECTION = "COLLECTION";
export const CONLLECTION_ALL_IMAGES = "CONLLECTION_ALL_IMAGES";
export const CONLLECTION_ALL_IMAGES_DETAILS = "CONLLECTION_ALL_IMAGES_DETAILS";
